# Generated by Django 3.2.9 on 2022-02-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websurat', '0006_alter_files_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='ket',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='perihal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
