# Generated by Django 3.2.9 on 2022-02-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websurat', '0007_auto_20220206_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='kode_surat',
            field=models.CharField(choices=[('D/ATIDP/II/2022', 'Direktur'), ('WD/ATIDP/II/2022', 'Wakil Direktur'), ('TMS/ATIDP/II/2022', 'Mesin Otomotif'), ('TSP/ATIDP/II/2022', 'Teknik Sipil'), ('W', 'Elektronika?')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nomor_surat',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
