# Generated by Django 3.2.9 on 2022-02-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websurat', '0008_auto_20220207_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='kode_surat',
            field=models.CharField(choices=[('/D/ATIDP/II/2022', 'Direktur'), ('/WD/ATIDP/II/2022', 'Wakil Direktur'), ('/TMS/ATIDP/II/2022', 'Mesin Otomotif'), ('/TSP/ATIDP/II/2022', 'Teknik Sipil'), ('/W', 'Elektronika?')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nomor_surat',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
