# Generated by Django 3.2.9 on 2022-04-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websurat', '0010_alter_surat_kode_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='bulan_surat',
            field=models.CharField(choices=[('I/2022', 'I'), ('II/2022', 'II'), ('III/2022', 'III'), ('IV/2022', 'IV'), ('V/2022', 'V'), ('VI/2022', 'VI'), ('VII/2022', 'VII'), ('VIII/2022', 'VIII'), ('IX/2022', 'IX'), ('X/2022', 'X'), ('XI/2022', 'XI'), ('XII/2022', 'XII')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='pdf',
            field=models.FileField(upload_to='doc'),
        ),
        migrations.AlterField(
            model_name='surat',
            name='kode_surat',
            field=models.CharField(choices=[('/D/ATIDP/', 'Direktur'), ('/WD/ATIDP/', 'Wakil Direktur'), ('/TMS/ATIDP/', 'Mesin Otomotif'), ('/TSP/ATIDP/', 'Teknik Sipil'), ('/ELK/ATIDP/', 'Teknik Elektronika'), ('/AKD/ATIDP/', 'Akademik'), ('/KMS/ATIDP/', 'Kemahasiswaan'), ('/LPM/ATIDP/', 'LPM'), ('/LPPM/ATIDP/', 'LPPM'), ('/SR.PR/ATIDP/', 'Sarana Prasarana'), ('/KJS/ATIDP/', 'Kerja Sama'), ('/SDM/ATIDP/', 'Sumber Daya Manusia'), ('/ADM/ATIDP/', 'Administrasi Umum'), ('/PMB/ATIDP/', 'PMB')], max_length=50, null=True),
        ),
    ]
